### ISSUE TITLE
No longer available on chrome web store

### ISSUE THREAD

**Issue by TheDoctor40** [banjophil/patreon-downloader#7]
Was setting up an older pc I have because I can't use my main machine right now. Unfortunately, chrome sync no longer pulls in the extension. Looking further, I can't find it on the chrome web store anymore, and searching via google I can find the link, but the store returns a 404. It seems the extension was removed from the store. Latest build in releases on here seems to be 0.1.1, but I remember the latest store version being newer. The latest commit message supports this. Would it be possible to get the newest build in releases which we can install manually?

**Comment by banjophil** [comment]
I've just pushed a built version of 0.1.4. You should be able to download that and install manually.

**Comment by banjophil** [comment]
I just updated the readme. As you can no longer filter by month, this extension is no longer useful to me. I would have duplicate copies of posts. Are you just archiving everything with a year filter once per year?

**Comment by TheDoctor40** [comment]
I archive post by post as they get published by the creators, so for me it's still quite useful. But the zip file is exactly what I needed, thank you!
